### ISSUE TITLE
可以把新版本上传下pub吗大佬

### ISSUE THREAD

**Issue by kenshin233** [jzoom/flutter_amap#5]

**Comment by jzoom** [comment]
家里的vpn坏了....
要是急用可以这么依赖:
```
flutter_amap:
    git: https://github.com/best-flutter/flutter_amap
```
![image](https://user-images.githubusercontent.com/6038236/44526276-15b36e80-a716-11e8-84b5-1942f15743a5.png)
有问题可以进qq群讨论 854192563
